@HostAddress = http://localhost:3000
@Token = 7MeOo0ZDz2

### Update Round Phase (Live)
POST {{HostAddress}}/
Accept: application/json
Content-Type: application/json

{
  "round": {
    "phase": "live"
  },
  "auth": {
    "token": "{{Token}}"
  }
}

### Update Round Phase (Over)
POST {{HostAddress}}/
Accept: application/json
Content-Type: application/json

{
  "round": {
    "phase": "over"
  },
  "auth": {
    "token": "{{Token}}"
  }
}