version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/src"
    schedule:
      interval: "weekly"
      day: "wednesday"
    groups:
      dotnet-sdk:
        patterns:
          - "*"

  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"
