version: 2
updates:
  - package-ecosystem: "dotnet-sdk"
    directory: "/src"
    schedule:
      interval: "weekly"
    
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
