# fly.toml app configuration file generated for discord-music-etctcw on 2025-02-28T21:28:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'discord-music-etctcw'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
  
[mounts]
  source = "discord_music_etctcw_data"
  destination = "/data"

