name: Test Linux

permissions:
  contents: write

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore DiscordMusic.slnx
        working-directory: ./src

      - name: Build
        run: dotnet build DiscordMusic.slnx --configuration Release --no-restore
        working-directory: ./src

      - name: Test
        run: dotnet test DiscordMusic.slnx --configuration Release --no-restore
        working-directory: ./src
